<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WSRV01" name="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test" tests="10" failures="2" timestamp="27 Sep 2016 10:11:30 GMT" time="66.837" errors="0">
  <testcase name="modifyPolicyUser_InValid" time="3.028" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="viewPolicyUser" time="3.049" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="deletePolicyUser_CheckDialog" time="3.064" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="deletePolicyUser_Yes" time="3.017" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="signIn" time="3.091" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="modifyPolicyUser_Valid" time="3.021" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="deletePolicyUser_No" time="3.131" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="signOut" time="2.006" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test">
    <failure type="java.lang.AssertionError" message="Sign Out Error">
      <![CDATA[java.lang.AssertionError: Sign Out Error
	at org.junit.Assert.fail(Assert.java:88)
	at com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test.signOut(PolicyUser_Test.java:951)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- signOut -->
  <testcase name="addPolicyUser_Invalid" time="3.874" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test"/>
  <testcase name="addPolicyUser_Valid" time="39.556" classname="com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test">
    <failure type="java.lang.AssertionError" message="Failed 1With Parameters:Policy User1,Policy User1 Description,role1;role2,,role1;role2">
      <![CDATA[java.lang.AssertionError: Failed 1With Parameters:Policy User1,Policy User1 Description,role1;role2,,role1;role2
	at org.junit.Assert.fail(Assert.java:88)
	at com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test.addPolicyUser_Valid(PolicyUser_Test.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- addPolicyUser_Valid -->
</testsuite> <!-- com.randtronics.dpm.filemanager.executionEngine.PolicyUser_Test -->
